server:
  port: 8085

spring:
  datasource:
    url: jdbc:oracle:thin:@oracle-docker:1521/XEPDB1 # host de oracle con Docker
    #url: jdbc:oracle:thin:@localhost:1521/XEPDB1 # host de oracle con Spring Boot
    username: GestorA                        #usuario creado oracle
    password: ORCL1234                      # mi contrase√±a creado en oracle
    driver-class-name: oracle.jdbc.OracleDriver  # driver de oracle
  jpa:
    hibernate:
      ddl-auto: update   # none | update | create | create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
  main:
    allow-bean-definition-overriding: true